server:
  port: 8092
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example-service
          uri: lb://example-service
          predicates:
            - Path=/examples/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
